server:
  port: 8765

spring:
  application:
    name: client-response

eureka:
  instance:
    instance-id: client-response-8765
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      # 向服务端注册自己
      defaultZone: http://localhost:8761/eureka/,http://localhost:8764/eureka/
