server:
  port: 8002

spring:
  application:
    name: eureka-client

eureka:
  instance:
    instance-id: eureka-client-8002
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      # 向服务端注册自己
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/, http://root:root@localhost:7003/eureka/
