server:
  port: 8004

spring:
  application:
    name: eureka-client

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://root:root@localhost:7001/eureka/, http://root:root@localhost:7002/eureka/