server:
  port: 8005

spring:
  application:
    name: eureka-open-feign-client-provider

eureka:
  instance:
    instance-id: eureka-open-feign-client-8005
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      # 向服务端注册自己
      defaultZone: http://localhost:7001/eureka/
