server:
  port: 8762

spring:
  application:
    name: client-request

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8764/eureka/