server:
  port: 8007

spring:
  application:
    name: eureka-hystrix-provider-8007

eureka:
  instance:
    instance-id: eureka-hystrix-provider-8007
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      # 向服务端注册自己
      defaultZone: http://localhost:7001/eureka/
