server:
  port: 8002

spring:
  application:
    name: eureka-ribbon-client-provider

eureka:
  instance:
    instance-id: eureka-ribbon-client-8002
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      # 向服务端注册自己
      defaultZone: http://localhost:7001/eureka/
